export default {
  blockedUser: false,
  identification: '',
  lang: {
    // identify screen
    'identify-title': 'Identifique-se',
    'identify-input': 'E-mail ou CPF/CNPJ (números)',
    'identify-error-not-found': 'Não foi possível verificar seu cadastro, tente novamente.',
    'identify-button': 'Continuar',
    // errors
    'identify-data-invalid': 'Dados inv&aacute;lidos, digite novamente!',
    'identify-error': 'N&atilde;o foi poss&iacute;vel verificar seu cadastro, tente novamente.',
    'identify-not-found': 'Usu&aacute;rio n&atilde;o encontrado, fa&ccedil;a seu cadastro.',
    'invalid-code': 'Autenticação incorreta',
    // authentication screen
    'authentication-title': 'Autenticação',
    'authentication-action-1': 'Você já comprou na nossa loja através do ',
    'authentication-action-2': 'Para sua segurança, selecione a opção correta para completar seu cadastro:',
    'authentication-question': 'Qual o seu sobrenome?',
    'authentication-go-back': '< Alterar CPF/CNPJ',
    // main screen
    'main-title': 'Autenticação',
    'main-action': 'Escolha uma das opções para se identificar:',
    'main-separator': 'ou utilize uma das opções abaixo',
    // password screen
    'password-title': 'E-mail e senha da loja',
    'password-button': 'E-mail e senha da loja',
    'password-button-cpf': 'CPF e senha da loja',
    'password-button-cnpj': 'CNPJ e senha da loja',
    'password-action': 'Informe sua senha.',
    'password-hide': 'Ocultar',
    'password-show': 'Mostrar',
    'password-input-label': 'Senha',
    'password-forget': 'Esqueci ou não tenho senha',
    // opt screen
    'otp-title': 'Código de Segurança',
    'otp-action': 'Informe o código de segurança que enviamos para seu e-mail.',
    'otp-receive': 'Receber código de segurança por e-mail',
    'otp-input-label': 'Código de segurança',
    // new password screen
    'new-password-label': 'Nova senha',
    'new-password-title': 'Cadastre uma nova senha',
    'new-password-action': 'Você receberá um código de segurança em seu e-mail para validar sua nova senha.',
    'new-password-submit': 'Salvar nova senha e continuar',
    'new-password-code-submit': 'Validar código de segurança',
    'new-password-success': 'Senha cadastrada com sucesso',
    title: 'Alterar senha',
    'new-password': 'Nova senha',
    'confirm-password': 'Confirmar nova senha',
    'must-contain': 'Sua senha deve conter: ',
    'min-characters': 'Mínimo de 8 caracteres',
    'min-number': 'Pelo menos 1 número',
    'min-letter': 'Pelo menos 1 letra',
    'save-password': 'Salvar nova senha',
    errors: {
      requirements: 'Senha não atende aos requisitos',
      equal: 'Senhas não são iguais',
      'create-password': 'Para salvar, crie uma nova senha',
      'confirm-password': 'Para salvar, confirme a senha',
      length: 'A senha deve ter no mínimo 8 caracteres.',
    },
    messages: {
      success: 'Senha alterada com sucesso',
      failure: 'Houve um erro ao alterar sua senha',
    },
    // general texts
    'other-option': 'Escolher outra opção',
    'go-back': 'Voltar',
    proceed: 'Continuar',
    // Blocked Screen
    'blocked-user': 'Por motivos de segurança bloqueamos o acesso por e-mail e senha durante 60 minutos.',
    'invalid-password': 'A nova senha deve possuir no mínimo 6 caracteres',
  },
  screen: 'Identification',
  resolution: 768,
};
